import Head from "next/head";

export default function HeadComp() {
    return(
        <Head>
          <title>Fabien Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}