import type { NextPage } from 'next'
import Head from 'next/head'
import Title from '../components/homescreenTitle'
import RsBar from '../components/rsBar'
import React, { useState, useEffect } from 'react'
import VerticalNavBar from '../components/navBarVertical'
const Home: NextPage = () => {

  // we use useEffect to add eventListener to the DOM
  // in dev mode, useEffect is called 2 times => some issues 
  // in prod mode, he has to be called 1 time
  useEffect(() => {
    console.log("useEffect Index init");
    const screenH = window.innerHeight;
    const SCROLL_PADDING = 0;

    document.getElementById("main")?.addEventListener('scroll', (e) => {
      const scrollTop =  document.getElementById("main")?.scrollTop;
      if (scrollTop) {
        if ((scrollTop + SCROLL_PADDING) > (2*screenH - 1)) {
          console.log("en bas");
          const currentSpan =  document.querySelector("a[href='#about']")?.children[0];
          changeId(currentSpan, "about")

        } else if ((scrollTop + SCROLL_PADDING) > (screenH - 1)) {
          console.log("middle");
          const currentSpan =  document.querySelector("a[href='#projects']")?.children[0];
          changeId(currentSpan, "projects")

        } else {
          console.log("begin");
          const currentSpan =  document.querySelector("a[href='#welcome']")?.children[0];
          changeId(currentSpan, "welcome");
        }
      }
   }, {passive: true})
  })

  return (
      <div>
        <Head>
          <title>Fabien Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <VerticalNavBar />      
        <RsBar/>
        
      <main id='main'>
        <section id="welcome" className='classicSection'>
          <Title/>
        </section>
        
        <section id="projects" className='bg-slate-100 bg-blend-exclusion text-red-600 text-4xl'>
          <div className="leftSticky">
            Project
            <div className="card"></div>
          </div>
          <div className="rightScroll">
            <div className="detail">    
               Detail .... 
              <div className="card"></div>
            </div>

            <div className="detail">
              Detail .... 
              <div className="card"></div>
            </div>

            <div className="detail">
              Detail .... 
              <div className="card"></div>
            </div>

          </div>
        </section>

        <section id="projects" className='bg-slate-100 bg-blend-exclusion text-red-600 text-4xl'>
          <div className="rightScroll">
            <div className="detail">    
               Detail .... 
              <div className="card"></div>
            </div>

            <div className="detail">
              Detail .... 
              <div className="card"></div>
            </div>

            <div className="detail">
              Detail .... 
              <div className="card"></div>
            </div>

          </div>
          <div className="leftSticky">
            Project
          <div className="card"></div>
          </div>

        </section>

      <section className='bg-green-100 bg-blend-exclusion text-red-600 text-4xl classicSection'>
          <div className="parallax_layer">
            Projects
          </div>
        </section>
        <section id="about" className='classicSection'>
          <button className='bg-Orange'>Button</button>
          <button className='bg-Green'>Button</button>
          <footer className='MediumEmphasis'>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
            </a>
          </footer>

        </section>
      </main>
      </div>
  )
}

export default Home

function changeId(currentSpan: any, path: string) {
    if (currentSpan && currentSpan.id != "active") {
            console.log("change id")
            document.getElementById("active")?.removeAttribute("id");
            currentSpan.setAttribute("id", "active");
            // if we want to update the url
            // window.location.hash = path;
    }
}