import type { NextPage } from 'next'
import loadConfig from 'next/dist/server/config'
import Head from 'next/head'
import Title from '../components/homescreenTitle'
import RsBar from '../components/rsBar'
import React, { useState, useEffect } from 'react'

const Home: NextPage = () => {

  useEffect(() => {
    console.log("caca");
    window.addEventListener('load', (event) => {
      console.log(event);
    })
  })

  return (
      <div className="snap-y overflow-y-scroll snap-mandatory w-screen h-screen">
      <Head>
        <title>Fabien's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <section>
          <Title/>
        </section>

        <section className='bg-slate-50'>
          {/* we put the RS bar here because of the mix-blend-mode needs access to background/parent */}
          <RsBar/>
        </section>

        <section>
          <button className='bg-Orange'>Button</button>
          <button className='bg-Green'>Button</button>
      <footer className='MediumEmphasis'>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
        </a>
      </footer>

        </section>
           </div>
  )
}

export default Home
