import type { NextPage } from 'next'
import Head from 'next/head'
import Title from '../components/homescreenTitle'
import RsBar from '../components/rsBar'
import React, { useState, useEffect } from 'react'
import VerticalNavBar from '../components/navBarVertical'
import Project from '../pages/projects'
const Home: NextPage = () => {

  // we use useEffect to add eventListener to the DOM
  // in dev mode, useEffect is called 2 times => some issues 
  // in prod mode, he has to be called 1 time
  useEffect(() => {
    console.log("useEffect Index init");
    const screenH = window.innerHeight;
    const SCROLL_PADDING = 0;

    document.getElementById("main")?.addEventListener('scroll', (e) => {
      const scrollTop =  document.getElementById("main")?.scrollTop;
      screenSplittingScroll(scrollTop);
      if (scrollTop) {
        if ((scrollTop + SCROLL_PADDING) > (2*screenH - 1)) {
          console.log("en bas");
          const currentSpan =  document.querySelector("a[href='#about']")?.children[0];
          changeId(currentSpan, "about")

        } else if ((scrollTop + SCROLL_PADDING) > (screenH - 1)) {
          console.log("middle");
          const currentSpan =  document.querySelector("a[href='#projects']")?.children[0];
          changeId(currentSpan, "projects")

        } else {
          console.log("begin");
          const currentSpan =  document.querySelector("a[href='#welcome']")?.children[0];
          changeId(currentSpan, "welcome");
        }
      }
   }, {passive: true})
  })

  return (
      <div>
        <Head>
          <title>Fabien Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <VerticalNavBar />      
        <RsBar/>
        

        {/* <div className="sticky top-0">heyyy</div> */}

      <main id='main'>
        <div className="sticky top-0">heyyy</div>
        <section className='bg-red-900'>

         <div className="w-1/2 h-1/2 border-cyan-900 bg-green-500 sticky top-0">
          sdxzs
          ezxsssxs
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Error voluptatem quasi recusandae distinctio architecto doloremque similique delectus, porro maxime aperiam in, dolore aliquid est ipsam, quaerat quas eos eligendi deleniti!
        </div>
 dcddcdddddddddddd
        </section>
        <section className='bg-green-200 flex-row h-fit justify-start'>
          <div className="staticClass">Project</div>
          <div className="desc">
            DESC
            <div className="detail">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quidem necessitatibus saepe amet sapiente sit blanditiis ad, repellendus, totam perspiciatis placeat doloremque numquam nesciunt beatae fugit nam ut facere consectetur.
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quidem necessitatibus saepe amet sapiente sit blanditiis ad, repellendus, totam perspiciatis placeat doloremque numquam nesciunt beatae fugit nam ut facere consectetur.
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quidem necessitatibus saepe amet sapiente sit blanditiis ad, repellendus, totam perspiciatis placeat doloremque numquam nesciunt beatae fugit nam ut facere consectetur.
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quidem necessitatibus saepe amet sapiente sit blanditiis ad, repellendus, totam perspiciatis placeat doloremque numquam nesciunt beatae fugit nam ut facere consectetur.
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quidem necessitatibus saepe amet sapiente sit blanditiis ad, repellendus, totam perspiciatis placeat doloremque numquam nesciunt beatae fugit nam ut facere consectetur.
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quidem necessitatibus saepe amet sapiente sit blanditiis ad, repellendus, totam perspiciatis placeat doloremque numquam nesciunt beatae fugit nam ut facere consectetur.
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio quidem necessitatibus saepe amet sapiente sit blanditiis ad, repellendus, totam perspiciatis placeat doloremque numquam nesciunt beatae fugit nam ut facere consectetur.
            </div>
            <div className="detail"></div>
            <div className="detail"></div>
          </div>
        </section>

        <section id="welcome">
          <Title/>
        </section>
                <section id="projects" className='bg-slate-50 bg-blend-exclusion text-red-600 text-4xl'>
          <div className="parallax_layer">
            Projects
          </div>
        </section>
      <section id="projects" className='bg-slate-50 bg-blend-exclusion text-red-600 text-4xl'>
          <div className="parallax_layer">
            Projects
          </div>
        </section>
        <section id="about">
          <button className='bg-Orange'>Button</button>
          <button className='bg-Green'>Button</button>
          <footer className='MediumEmphasis'>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
            </a>
          </footer>

        </section>
        <section>

            <Project />
        </section>
        

      </main>
      </div>
  )
}

export default Home

function changeId(currentSpan: any, path: string) {
    if (currentSpan && currentSpan.id != "active") {
            console.log("change id")
            document.getElementById("active")?.removeAttribute("id");
            currentSpan.setAttribute("id", "active");
            // if we want to update the url
            // window.location.hash = path;
    }
}

function screenSplittingScroll(scrollTop: any) {
 let staticDiv = document.querySelector('.static');  
 console.log(staticDiv);
 console.log("scroll");
//  staticDiv?.setAttribute('style', `margin-top: ${scrollTop}px`)
}